version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
# jobs:
#   runner-test:
#     machine: true
#     resource_class: mrugeshpatelcumulative/cumulativeapps
#     steps:
#       - run: echo "Hi I'm on Runners!"

# version: 2
jobs:
  build:
    working_directory: ~/Mrugesh
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e6:49:0d:ff:ae:0c:d4:3b:7f:21:b0:8e:09:bc:f1:77"
      - run: echo "add_file"
          # name: echo "add_file"
          # command: "cd /var/www/html/Mrugesh/ && touch test.txt && exit"  

  # deploy:
  #   dev:
  #     branch: dev
  #     commands:
  #       - ssh $USER_NAME@$USER_IP 'cd /var/www/html/Mrugesh/ && data.txt'