version: 2.1

jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e6:49:0d:ff:ae:0c:d4:3b:7f:21:b0:8e:09:bc:f1:77"
      - checkout
      - run:
          name: Push Staging repo
          command: |
            chmod 755 .circleci/deploy.sh
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: ./.circleci/deploy.sh

workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main