# version: 2

# jobs:
#     build:
#     #...
#     deploy:
#     machine:
#         enabled: true
#     steps:
#         - run:
#             name: Deploy Over SSH
#             command: |
#             ssh $SSH_USER@$SSH_HOST "cd /var/www/html/Mrugesh/ && touch test.txt && exit"

# workflows:
#     version: 2
#     build-and-deploy:
#     jobs:
#         - build
#         - deploy:
#             requires:
#             - build # only deploy once build job has completed
#             filters:
#             branches:
#                 only: main # only deploy on the main branch

# version: 2.1
# jobs:
#   build:
#     working_directory: ~/Mrugesh
#     machine:
#       image: ubuntu-2204:2022.04.1
#     steps:
#       - checkout
#       - add_ssh_keys:
#           fingerprints:
#             - "65:e1:e6:3e:69:08:e6:83:d5:96:fb:41:7e:f5:d3:4e"
#       - run:
#           name: "Testing"
#           command: echo "Hi"
#       - run: ssh $SSH_USER@$SSH_HOST "pwd"
#       - run:
#           name: "Testing"
#           command: "pwd"
      # - run:
      #     name: add_file
      #     command: "cd /var/www/html/Mrugesh/ && touch test.txt && exit"
# version: 2
# jobs:
#   build:
#     working_directory: ~/Mrugesh
#   deploy-job:
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "e6:49:0d:ff:ae:0c:d4:3b:7f:21:b0:8e:09:bc:f1:77"
#       - run:
#           name: add_file
#           command: "cd /var/www/html/Mrugesh/ && touch test.txt && exit"  

version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e6:49:0d:ff:ae:0c:d4:3b:7f:21:b0:8e:09:bc:f1:77"
      - run:
          name: Update known hosts
          command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: "Testing"
          command: echo "Hi"
      - run: ssh $SSH_USER@$SSH_HOST "./deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main